name: observer
replicas: 1
container:
  image: ghcr.io/salex-org/smart-home-observer
  imagePullSecrets:
    - name: ghcr-secret
config:
  interval: 10
  hmip:
    secret: hmip-credentials
  wordpress:
    secret: wordpress-credentials
    endpoint: https://holzwerken.salex.org
  influx:
    bucket: homematic
    organization: salex
    ingress:
      enabled: true
      organization: salex.home
      host: influx.observer.naboo.salex.home
  grafana:
    enabled: false # set to true to deploy grafana datasource, dashboards and alerts
    instance: "" # add a label named 'grafana' to the instanceSelector section in spec of all grafana resources
influxdb2:
  adminUser:
    organization: salex
    bucket: homematic
    retention_policy: 731d
    existingSecret: influx-credentials
