version: '3'

services:
  influx:
    image: influxdb:2.5.1
    ports:
      - '8086:8086'
    volumes:
      - ./influx/data:/var/lib/influxdb2
      - ./influx/config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=local
      - DOCKER_INFLUXDB_INIT_PASSWORD=localsecret
      - DOCKER_INFLUXDB_INIT_ORG=smart-home-observer
      - DOCKER_INFLUXDB_INIT_BUCKET=climate

  mosquitto:
    image: eclipse-mosquitto:2.0.15
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/log:/mosquitto/log

  grafana:
    image: grafana/grafana-oss:9.3.1
    ports:
      - '3000:3000'
    user: '472'
    volumes:
      - ./grafana/data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=local
      - GF_SECURITY_ADMIN_PASSWORD=localsecret
