version: '3'

networks:
  smart-home:

services:
  observer:
    container_name: smart-home-observer
    image: smart-home-observer:0.0.0
    depends_on:
      influx:
        condition: service_healthy
    ports:
      - '8080:8080'
    networks:
      - smart-home
    environment:
      - INFLUX_URL=http://influx:8086
      - INFLUX_TOKEN=localadmintoken
      - INFLUX_CLIMATE_BUCKET=smart-home
      - INFLUX_CONSUMPTION_BUCKET=smart-home
      - INFLUX_ORGANIZATION=salex
    env_file:
      - .env.observer
    healthcheck:
      test: [ "CMD", "/healthcheck" ]
      interval: 10s
      timeout: 10s
      retries: 10

  influx:
    container_name: smart-home-influx
    image: influxdb:2.5.1
    ports:
      - '8086:8086'
    volumes:
      - ./influx/data:/var/lib/influxdb2d
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=local
      - DOCKER_INFLUXDB_INIT_PASSWORD=localsecret
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=localadmintoken
      - DOCKER_INFLUXDB_INIT_ORG=salex
      - DOCKER_INFLUXDB_INIT_BUCKET=smart-home
    networks:
      - smart-home
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8086/ping" ]
      interval: 3s
      timeout: 60s
      retries: 1


