version: '3'

networks:
  smart-home:

services:
  vault:
    container_name: smart-home-vault
    image: hashicorp/vault:1.13.0
    user: ${SMART_HOME_USER}
    cap_add:
      - IPC_LOCK
    command:
      - server
    ports:
      - '8200:8200'
    networks:
      - smart-home
    volumes:
      - ./vault/config:/vault/config
      - ./vault/logs:/vault/logs
      - ./vault/data:/vault/file

  observer:
    container_name: smart-home-observer
    image: smart-home-observer:0.0.0
    depends_on:
      influx:
        condition: service_healthy
    ports:
      - '8081:8080'
    networks:
      - smart-home
    volumes:
      - ./observer/config:/config
    environment:
      CONFIG_DECRYPTION_ENABLED: false

  influx:
    container_name: smart-home-influx
    image: influxdb:2.5.1
    ports:
      - '8086:8086'
    volumes:
      - ./influx/data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=local
      - DOCKER_INFLUXDB_INIT_PASSWORD=localsecret
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=localadmintoken
      - DOCKER_INFLUXDB_INIT_ORG=salex
      - DOCKER_INFLUXDB_INIT_BUCKET=smart-home
    networks:
      - smart-home
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8086/ping" ]
      interval: 3s
      timeout: 60s
      retries: 1

  grafana:
    container_name: smart-home-grafana
    image: grafana/grafana-oss:9.3.1
    depends_on:
      influx:
        condition: service_healthy
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=local
      - GF_SECURITY_ADMIN_PASSWORD=localsecret
    networks:
      - smart-home

