version: '3'

services:
  observer:
    image: ghcr.io/salex-org/smart-home-observer:0.0.0
    user: ${SMART_HOME_USER_OBSERVER}
    # Detach from container with "CTRL-p CTRL-q" when startet with "-i -t" without stopping the container
    stdin_open: true    # docker run -i
    tty: true           # docker run -t
    ports:
      - '8081:8080'
    networks:
      - smart-home-observer
    volumes:
      - ./observer/config:/config

  influx:
    image: influxdb:2.5.1
    user: ${SMART_HOME_USER_INFLUX}
    ports:
      - '8086:8086'
    volumes:
      - ./influx/data:/var/lib/influxdb2
      - ./influx/config:/etc/influxdb2
    networks:
      - smart-home-observer

  mosquitto:
    image: eclipse-mosquitto:2.0.15
    user: ${SMART_HOME_USER_MOSQUITTO}
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/log:/mosquitto/log
    networks:
      - smart-home-observer

  grafana:
    image: grafana/grafana-oss:9.3.1
    user: ${SMART_HOME_USER_GRAFANA}
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/data:/var/lib/grafana
    networks:
      - smart-home-observer

networks:
  smart-home-observer: