database:
  url: 'http://smart-home-influx:8086'
  token: 'localadmintoken'
  org: 'smart-home'
  buckets:
    consumption: 'consumption'
mqtt-broker:
  url: 'tcp://smart-home-mosquitto:1883'
  username: 'local'
  password: 'localsecret'
  topics:
    consumption:
      electricity: 'consumption.electricity.main'
      gas: 'consumption.gas.main'