{{- if .Values.config.grafana.enabled }}
{{- $influxSecret := lookup "v1" "Secret" .Release.Namespace .Values.influxdb2.adminUser.existingSecret }}
{{- if not $influxSecret }}
{{- fail "InfluxDB Secret not found – deploy Influx first" }}
{{- end }}
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: {{ .Values.name }}-datasource
  namespace: {{ .Release.Namespace }}
spec:
  allowCrossNamespaceImport: true
  instanceSelector:
    matchLabels:
      grafana: naboo
  valuesFrom:
    - targetPath: "secureJsonData.token"
      valueFrom:
        secretKeyRef:
          name: "influx-credentials"
          key: "admin-token"
  datasource:
    name: InfluxDB
    uid: smart-home-observer
    type: influxdb
    access: proxy
    url: http://{{ .Release.Name }}-influxdb2.{{ .Release.Namespace }}.svc.cluster.local
    jsonData:
      version: Flux
      organization: salex
{{- end }}