apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      imagePullSecrets:
        {{- if .Values.container.imagePullSecrets }}
        {{- toYaml .Values.container.imagePullSecrets | nindent 8 }}
        {{- end }}
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.container.image }}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /healthy
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 60
            failureThreshold: 3
          envFrom:
            - secretRef:
                name: {{ .Values.config.hmip.secret }}
            - secretRef:
                name: {{ .Values.config.wordpress.secret }}
            - configMapRef:
                name: {{ .Values.name }}-config
          env:
            - name: INFLUX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.influxdb2.adminUser.existingSecret }}
                  key: admin-token


