{{- if .Values.config.grafana.enabled }}
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: {{ .Values.name }}-folder
  namespace: {{ .Release.Namespace }}
spec:
  allowCrossNamespaceImport: true
  instanceSelector:
    matchLabels:
      {{ .Values.config.grafana.instance }}
  title: Smart Home
  uid: smart-home-observer
{{- end }}
