{{- if .Values.config.influx.ingress.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.name }}-influx-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Values.name }}-influx-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - {{ .Values.config.influx.ingress.organization }}
  commonName: {{ .Values.config.influx.ingress.host }}
  dnsNames:
    - {{ .Values.config.influx.ingress.host }}
  issuerRef:
    name: cluster-ca-issuer
    kind: ClusterIssuer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}-influx
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.config.influx.ingress.host }}
      secretName: {{ .Values.name }}-influx-cert
  rules:
      - host: {{ .Values.config.influx.ingress.host }}
        http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: {{ .Release.Name }}-influxdb2
                  port:
                    number: 80
  {{- end }}