apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}-influx-init
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}-influx-init
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: influx-init
          image: ghcr.io/salex-org/backup:0.0.4
          command: ["/bin/sh", "-c"]
          args:
            - |
              CONSUMPTION_BUCKET_ID=$(influx bucket list --name consumption --json 2>/dev/null | jq -r '.[0].id // empty')
              if [ -z "$CONSUMPTION_BUCKET_ID" ]; then
                CONSUMPTION_BUCKET_ID=$(influx bucket create --name consumption --retention 365d --json | jq -r ".id")
                INFLUX_ORG_ID=$(influx org list --json | jq -r '.[] | select(.name == "'"$INFLUX_ORG"'") | .id')
                curl -sS -X POST "$INFLUX_HOST/api/v2/authorizations" \
                  -H "Authorization: Token $INFLUX_TOKEN" \
                  -H "Content-Type: application/json" \
                  -d "{
                      \"orgID\": \"$INFLUX_ORG_ID\",
                      \"token\": \"$CONSUMPTION_TOKEN\",
                      \"description\": \"token for bucket 'consumption'\",
                      \"permissions\": [
                        {
                          \"action\": \"write\",
                          \"resource\": {
                            \"type\": \"buckets\",
                            \"id\": \"$CONSUMPTION_BUCKET_ID\"
                          }
                        }
                      ]
                  }"
              fi
          env:
            - name: INFLUX_ORG
              value: salex
            - name: INFLUX_HOST
              value: http://{{ .Release.Name }}-influxdb2.{{ .Release.Namespace }}.svc.cluster.local
            - name: INFLUX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.influxdb2.adminUser.existingSecret }}
                  key: admin-token
            - name: CONSUMPTION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.influxdb2.adminUser.existingSecret }}
                  key: consumption-token
      imagePullSecrets:
        {{- if .Values.container.imagePullSecrets }}
        {{- toYaml .Values.container.imagePullSecrets | nindent 8 }}
        {{- end }}
      restartPolicy: OnFailure