{{- if .Values.config.grafana.enabled }}
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaAlertRuleGroup
metadata:
  name: {{ .Release.Name }}-vivaria-alerts
  namespace: {{ .Release.Namespace }}
spec:
  folderRef: {{ .Release.Name }}-folder
  allowCrossNamespaceImport: true
  instanceSelector:
    matchLabels:
      grafana: {{ .Values.config.grafana.instance }}
  interval: 5m
  rules:
    - uid: e64b653e-d33a-45cd-81e8-f72f5e070c7c
      title: Terrarium light faulty
      labels:
        smart_home_section: vivaria
      condition: C
      data:
        - refId: A
          relativeTimeRange:
            from: 86400
            to: 0
          datasourceUid: smart-home-observer-homematic
          model:
            datasource:
              type: influxdb
              uid: homematic-influx
            groupBy:
              - params:
                  - $__interval
                type: time
              - params:
                  - previous
                type: fill
            intervalMs: 1000
            maxDataPoints: 43200
            measurement: device
            orderByTime: ASC
            policy: default
            query: SELECT "current_power_consumption" FROM "device" WHERE ("device_id"::tag = '3014F711A0003AA0C98D95CC' AND "switched_on"::field = TRUE) AND $timeFilter
            rawQuery: true
            refId: A
            resultFormat: time_series
            select:
              - - params:
                    - current_power_consumption
                  type: field
                - params: []
                  type: last
            tags:
              - condition: AND
                key: device_id::tag
                operator: =
                value: 3014F711A0003AA0C98D95CC
              - condition: AND
                key: switched_on::field
                operator: =
                value: select tag value
        - refId: C
          relativeTimeRange:
            from: 86400
            to: 0
          datasourceUid: __expr__
          model:
            conditions:
              - evaluator:
                  params:
                    - 100
                    - 115
                  type: outside_range
                operator:
                  type: and
                query:
                  params:
                    - C
                reducer:
                  params: []
                  type: last
                type: query
            datasource:
              type: __expr__
              uid: __expr__
            expression: B
            intervalMs: 1000
            maxDataPoints: 43200
            refId: C
            type: threshold
        - refId: B
          datasourceUid: __expr__
          model:
            conditions:
              - evaluator:
                  params:
                    - 0
                    - 0
                  type: gt
                operator:
                  type: and
                query:
                  params: []
                reducer:
                  params: []
                  type: avg
                type: query
            datasource:
              name: Expression
              type: __expr__
              uid: __expr__
            expression: A
            intervalMs: 1000
            maxDataPoints: 43200
            reducer: last
            refId: B
            type: reduce
      noDataState: NoData
      execErrState: OK
      for: 1h
      annotations:
        summary: The power consumption of the terrarium lights is out of normal range while switched on. Maybe a lamp is broken.
      isPaused: false
    - uid: ce583edd-359b-4959-99db-c4409024ea17
      title: Aquarium light faulty
      labels:
        smart_home_section: vivaria
      condition: C
      data:
        - refId: A
          relativeTimeRange:
            from: 86400
            to: 0
          datasourceUid: smart-home-observer-homematic
          model:
            datasource:
              type: influxdb
              uid: homematic-influx
            groupBy: []
            intervalMs: 1000
            maxDataPoints: 43200
            measurement: device
            orderByTime: ASC
            policy: default
            query: SELECT "current_power_consumption" FROM "device" WHERE ("device_id"::tag = '3014F711A0003AA0C98D95C9' AND "switched_on"::field = TRUE) AND $timeFilter
            rawQuery: true
            refId: A
            resultFormat: time_series
            select:
              - - params:
                    - current_power_consumption
                  type: field
            tags:
              - condition: AND
                key: device_id::tag
                operator: =
                value: 3014F711A0003AA0C98D95CC
              - condition: AND
                key: switched_on::field
                operator: =
                value: select tag value
        - refId: C
          relativeTimeRange:
            from: 86400
            to: 0
          datasourceUid: __expr__
          model:
            conditions:
              - evaluator:
                  params:
                    - 7
                    - 10
                  type: outside_range
                operator:
                  type: and
                query:
                  params:
                    - C
                reducer:
                  params: []
                  type: last
                type: query
            datasource:
              type: __expr__
              uid: __expr__
            expression: B
            intervalMs: 1000
            maxDataPoints: 43200
            refId: C
            type: threshold
        - refId: B
          relativeTimeRange:
            from: 86400
            to: 0
          datasourceUid: __expr__
          model:
            conditions:
              - evaluator:
                  params:
                    - 0
                    - 0
                  type: gt
                operator:
                  type: and
                query:
                  params: []
                reducer:
                  params: []
                  type: avg
                type: query
            datasource:
              name: Expression
              type: __expr__
              uid: __expr__
            expression: A
            intervalMs: 1000
            maxDataPoints: 43200
            reducer: last
            refId: B
            type: reduce
      noDataState: OK
      execErrState: Error
      for: 1h
      annotations:
        summary: The power consumption of the aquarium light is out of normal range while switched on. Maybe a lamp is broken.
      isPaused: false
    - uid: bed43213-7917-4195-88e2-27a48f7fbaa9
      title: Aquarium pump faulty
      labels:
        smart_home_section: vivaria
      condition: C
      data:
        - refId: A
          relativeTimeRange:
            from: 86400
            to: 0
          datasourceUid: smart-home-observer-homematic
          model:
            datasource:
              type: influxdb
              uid: homematic-influx
            groupBy:
              - params:
                  - $__interval
                type: time
              - params:
                  - previous
                type: fill
            intervalMs: 1000
            maxDataPoints: 43200
            measurement: device
            orderByTime: ASC
            policy: default
            query: SELECT "current_power_consumption" FROM "device" WHERE ("device_id"::tag = '3014F711A0003AA0C98D875B' AND "switched_on"::field = TRUE) AND $timeFilter
            rawQuery: true
            refId: A
            resultFormat: time_series
            select:
              - - params:
                    - current_power_consumption
                  type: field
                - params: []
                  type: last
            tags:
              - condition: AND
                key: device_id::tag
                operator: =
                value: 3014F711A0003AA0C98D95CC
              - condition: AND
                key: switched_on::field
                operator: =
                value: select tag value
        - refId: C
          relativeTimeRange:
            from: 86400
            to: 0
          datasourceUid: __expr__
          model:
            conditions:
              - evaluator:
                  params:
                    - 4.5
                    - 6.5
                  type: outside_range
                operator:
                  type: and
                query:
                  params:
                    - C
                reducer:
                  params: []
                  type: last
                type: query
            datasource:
              type: __expr__
              uid: __expr__
            expression: B
            intervalMs: 1000
            maxDataPoints: 43200
            refId: C
            type: threshold
        - refId: B
          datasourceUid: __expr__
          model:
            conditions:
              - evaluator:
                  params:
                    - 0
                    - 0
                  type: gt
                operator:
                  type: and
                query:
                  params: []
                reducer:
                  params: []
                  type: avg
                type: query
            datasource:
              name: Expression
              type: __expr__
              uid: __expr__
            expression: A
            intervalMs: 1000
            maxDataPoints: 43200
            reducer: last
            refId: B
            type: reduce
      noDataState: OK
      execErrState: Error
      for: 1h
      annotations:
        summary: The power consumption of the aquarium pump is out of normal range while switched on. Maybe it is broken.
      isPaused: false

  {{- end }}