name: Create release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number to release'
        required: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    name: Create a release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set version in docker-compose.yml
        uses: fjogeleit/yaml-update-action@v0.12.3
        with:
          valueFile: docker/prod/docker-compose.yml
          propertyPath: 'services.observer.image'
          value: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.version }}
          commitChange: false

      - name: Create tag
        run: |
          git config --global user.email "buildmanager@salex.org"
          git config --global user.name "Bob the Builder"
          git add docker/prod/docker-compose.yml
          git commit -m "updating version to ${{ github.event.inputs.version }} in docker-compose"
          git tag -a v${{ github.event.inputs.version }} -m "tagging version ${{ github.event.inputs.version }}"
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          # Use PERSONAL_ACCESS_TOKE (with write permission) instead of GITHUB_TOKEN to trigger other worflows reafcting on events !!!

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          # Use PERSONAL_ACCESS_TOKE (with write permission) instead of GITHUB_TOKEN to trigger other worflows reafcting on events !!!
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: Release v${{ github.event.inputs.version }}
          body: |
            Release v${{ github.event.inputs.version }}
          draft: false
          prerelease: false

      - name: Package scripts
        run: |
          mkdir bin
          tar cfvz ./bin/scripts.tar.gz -C docker/prod .

      - name: Upload scripts asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/scripts.tar.gz
          asset_name: scripts.tar.gz
          asset_content_type: application/gzip